# Generated by Django 3.2 on 2021-06-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20210607_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerdata',
            name='SRM_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='beerdata',
            name='SRM_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='beerdata',
            name='style_groups',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beerdata',
            name='style_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beerdata',
            name='style_key_family',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beerdata',
            name='style_number',
            field=models.IntegerField(),
        ),
    ]
