# Generated by Django 3.2 on 2021-06-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0005_remove_beermodel_ibu'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerdata',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='beerdata',
            name='food_pair',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='beermodel',
            name='abv',
            field=models.FloatField(choices=[('2.5 - 4.5', 'Low Alcohol'), ('4.6 - 7.0', 'Medium Alcohol'), ('7.1 - 20', 'High Alcohol')], default='2.5 - 4.5'),
        ),
        migrations.AlterField(
            model_name='beermodel',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others...')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='beermodel',
            name='srm',
            field=models.FloatField(choices=[('0', 'Light Colour'), ('1', 'Dark Colour')], default='0'),
        ),
    ]
