# Generated by Django 3.2 on 2021-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0006_auto_20210627_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerdata',
            name='desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='beerdata',
            name='food_pair',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
