# Generated by Django 3.2 on 2021-06-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0007_auto_20210627_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerdata',
            name='style_groups',
        ),
        migrations.RemoveField(
            model_name='beerdata',
            name='style_key',
        ),
        migrations.RemoveField(
            model_name='beerdata',
            name='style_number',
        ),
    ]
